import { jsPDF } from 'jspdf';

export function generatePDF(data: any): Buffer {
  try {
    // Create PDF document
    const pdf = new jsPDF({ orientation: "p", unit: "pt", format: "a4" });
    
    // Add title
    pdf.setFontSize(20);
    pdf.text('Pulse Dashboard Report', 50, 50);
    
    // Add client info
    pdf.setFontSize(12);
    let yPosition = 80;
    
    if (data.clientLabel) {
      pdf.text(`Client: ${data.clientLabel}`, 50, yPosition);
      yPosition += 20;
    }
    
    // Add generation date
    const today = new Date();
    pdf.text(`Generated: ${today.toLocaleDateString()}`, 50, yPosition);
    yPosition += 30;
    
    // Add note about data visualization
    pdf.setFontSize(10);
    pdf.text('Note: This is a simplified PDF export. Charts and visualizations', 50, yPosition);
    pdf.text('are best viewed in the interactive dashboard.', 50, yPosition + 15);
    yPosition += 50;
    
    // Add footer
    pdf.setFontSize(8);
    pdf.text('Generated by Pulse Dashboard™', 50, pdf.internal.pageSize.getHeight() - 30);
    
    // Return as Buffer
    const pdfArrayBuffer = pdf.output('arraybuffer');
    return Buffer.from(pdfArrayBuffer);
    
  } catch (error) {
    throw new Error(`PDF generation failed: ${error}`);
  }
}